### ISSUE TITLE
Clear all block inventories after MECHA

### ISSUE THREAD

**Issue by Braekpo1nt** [Braekpo1nt/MCTManager#150]
## Describe the bug
Players can take an item out of a chest, place it in a nearby decorative barrel, and go back to that barrel to retrieve the item in the next round. 

## To Reproduce
- Start MECHA
- Take an item out of a chest, and place it in a barrel
- Stop mecha
- Start mecha
- Go back to that barrel and see that the item is still in it

## Expected behavior
MECHA should clear all items from all inventories in the map

## Suggested fix
Do a loop of all blocks in the bounds of MECHA, check if it has an inventory, and clear that inventory. 

**OR**

Reset the map entirely by replacing the entire structure with a copy of the original (this is probably much more difficult, so this likely isn't a good solution for MCT#2)

## Definition of Done
- [ ] When you start a game of MECHA, no items exist in any inventories except the chests that are meant to have random loot generated in them

**Comment by rstlnmage** [comment]
Self: Investigate using this code
```
for (BlockState blockState : new Region(location1, location2).getBlocks()) {
    if (blockState instanceof InventoryHolder) {
        ((InventoryHolder) blockState).getInventory().clear();
    }
}
```
