### ISSUE TITLE
Make sure all event listeners have appropriate checks

### ISSUE THREAD

**Issue by Braekpo1nt** [Braekpo1nt/MCTManager#179]
## Description
Every event listener should have a set of checks before it does it's thing.

## Reason for Redesign
Some event listeners might be listening and being activated when they are not supposed to be

## Proposed Redesign
Do a find for all instances of `@EventHandler` and make sure that each one only runs when it is supposed to. Games should only 

## Definition of Done
*a detailed list of all tasks which must be completed for the issue to be called "done". Must use the checkbox bullet point `- [ ]`*
- [x] Event handlers have appropriate checks
  - [x] Game event listeners only run when the game is active
    - Note: Game event listeners are called by the true event listeners in `GameManger.java`. Make sure those have the appropriate checks as well. 
  - [x] Hub event listeners only run in the hub
  - [x] Global event listeners (which should be avoided when possible) have appropriate checks

**Comment by rstlnmage** [comment]
All games have active checks.

**Comment by rstlnmage** [comment]
@Braekpo1nt Confirm that Global listeners are set up correctly, then I think this is complete with no code changes needed

**Comment by Braekpo1nt** [comment]
No changes were needed, all checks are appropriate. @Braekpo1nt is a god among men, first try
