### ISSUE TITLE
Switch org.bukkit.ChatColor to org.bukkit.Color

### ISSUE THREAD

**Issue by Braekpo1nt** [Braekpo1nt/MCTManager#186]
## Description
Replace `org.bukkit.ChatColor` with `org.bukkit.Color` in all instances. 

## Reason for Redesign
`org.bukkit.ChatColor` is deprecated in favor of `org.bukkit.Color`. 

## Definition of Done
- [ ] all instances of `org.bukkit.ChatColor` are gone, replaced with `org.bukkit.Color`
- [ ] `ColorMap` is fixed to use the appropriate method names

**Comment by rstlnmage** [comment]
org.bukkit.ChatColor is not being deprecated. 
org.bukkit.Color does not have same color options (missing DARK_. LIGHT_. Gold)
