### ISSUE TITLE
Make armorstands and item frames uninteractable

### ISSUE THREAD

**Issue by Braekpo1nt** [Braekpo1nt/MCTManager#236]
## Description
When mecha is active, make sure player's can't take items from armor stands or picture frames, and can't rotate the items in picture frames either. 

## Definition of Done
- [x] Players can't right-click armor stands to remove the item from them and put it in their inventory
- [x] Players can't right-click armor stands to add an item to them
- [x] Players can't left-click armor stands to destroy them
- [x] Players can't right-click or left-click item frames to remove the item from them
- [x] Players can't right-click item frames to add an item to them
- [x] Players can't right-click item frames to rotate the item inside them

**Comment by rstlnmage** [comment]
Should be done now. Tested in game
