### ISSUE TITLE
If anchor doesn't exist, error occurs

### ISSUE THREAD

**Issue by Braekpo1nt** [Braekpo1nt/MCTManager#27]
### Description of bug
In `FootRaceGame::teleportPlayersToStartingPositions()`, if the multiverse anchor called `foot-race` does not exist, it throws a null-pointer exception.

### Suggested change
Make a specific setting that is persisted in the config document for MCTManager in the plugins folder. Allow users to specify anchors as starting positions, and if they don't exist don't start the game and alert the player who tried to start the game that they need to create an anchor.

**Comment by rstlnmage** [comment]
Another suggestion: Create a default anchor at onStart that can be modified in /mct arguments?
