### ISSUE TITLE
Unregister game event Listeners when not being used

### ISSUE THREAD

**Issue by Braekpo1nt** [Braekpo1nt/MCTManager#6]
## Description
When a game is not being played, the `Listener` implementation is not needed to listen to events anymore. Thus we need to unregister event the listeners with the `HandlerList.unregisterAll(Listener)` method like this:

```
//inside some implementation of Listener:
HandlerList.unregisterAll(this);
```

In every implementation of the `MCTGame` interface, there is a constructor which takes in an instance of the `Main` plugin (always called `plugin`). That makes a call to `plugin.getServer().getPluginManager().registerEvents(this, plugin);`. that's how events are registered (events are labeled with `@EventHandler`). 

You need to remove that `registerEvents` line from the constructor, and instead put it at the beginning of the `public void start(List<Player>)` method. This will make it so that the listeners are only registered at the beginning of the game. Then you need to add the `HandlerList.unregisterAll(this)` line to the beginning of the `public void stop()` method, so that when the game is stopped, the handlers are unregistered. 

## Definition of done
You need to do the above procedure for each of the following games:
- [x] `FootRaceGame.java`
- [x] `FinalGame.java`
- [x] `MechaGame.java`
- [x] `ParkourPathwayGame.java`
- [x] `SpleefGame.java`

## Extra Credit
You could also implement similar mechanisms in the following classes:
- [x] `VoteManger.java`

**Comment by Braekpo1nt** [comment]
Not needed yet

**Comment by Braekpo1nt** [comment]
You can use the `HandlerList.unregiesterAll(Listener)` static method to unregister all the events for a particular implementation of `Listener`

**Comment by rstlnmage** [comment]
I think I found all exit points from VoteManager where `HandlerList.unregisterAll(this);` needed to go
